[package]
name = "scratch"
version = "0.1"
lean_version = "3.4.2"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "895f1ae05228950b5ad99ee9ebb8cbd26f677e6e"}
